ktor:
  application:
    modules:
      - moe.bitt.ApplicationKt.module
  deployment:
    port: 8080

s3:
  bucket: ${S3_BUCKET}
  endpointUrl: ${S3_ENDPOINT_URL}
  region: ${S3_REGION:-ru-central1}
  accessKey: ${S3_ACCESS_KEY}
  secretKey: ${S3_SECRET_KEY}
