[versions]
kotlin = "2.2.20"
ktor = "3.3.0"
exposed = "0.61.0"
h2 = "2.3.232"
koin = "3.5.6"
postgres = "42.7.7"
logback = "1.5.13"
taskScheduling = "2.2.1"
jsoup = "1.18.1"
kotlinxDatetime = "0.6.1"
flyway = "8.2.0"
flyway-postgres = "10.18.2"
graphql = "8.2.1"
sentry = "7.18.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
graphql = { id = "com.expediagroup.graphql", version.ref = "graphql" }

[libraries]
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-core-jvm = { group = "io.ktor", name = "ktor-server-core-jvm", version.ref = "ktor" }
ktor-server-openapi = { group = "io.ktor", name = "ktor-server-openapi", version.ref = "ktor" }
ktor-server-swagger = { group = "io.ktor", name = "ktor-server-swagger", version.ref = "ktor" }
ktor-server-host-common = { group = "io.ktor", name = "ktor-server-host-common", version.ref = "ktor" }
ktor-server-status-pages = { group = "io.ktor", name = "ktor-server-status-pages", version.ref = "ktor" }
ktor-server-content-negotiation = { group = "io.ktor", name = "ktor-server-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { group = "io.ktor", name = "ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-netty = { group = "io.ktor", name = "ktor-server-netty", version.ref = "ktor" }
ktor-server-cio = { group = "io.ktor", name = "ktor-server-cio", version.ref = "ktor" }
ktor-server-config-yaml = { group = "io.ktor", name = "ktor-server-config-yaml", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }
ktor-server-metrics-micrometer = { group = "io.ktor", name = "ktor-server-metrics-micrometer", version.ref = "ktor" }
micrometer-registry-prometheus = { group = "io.micrometer", name = "micrometer-registry-prometheus", version = "1.10.3" }
ktor-server-call-id = { group = "io.ktor", name = "ktor-server-call-id", version.ref = "ktor" }
ktor-server-call-logging = { group = "io.ktor", name = "ktor-server-call-logging", version.ref = "ktor" }

# Ktor client
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { group = "io.ktor", name = "ktor-client-okhttp", version.ref = "ktor" }
ktor-client-content-negotiation = { group = "io.ktor", name = "ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-logging = { group = "io.ktor", name = "ktor-client-logging", version.ref = "ktor" }

exposed-core = { group = "org.jetbrains.exposed", name = "exposed-core", version.ref = "exposed" }
exposed-jdbc = { group = "org.jetbrains.exposed", name = "exposed-jdbc", version.ref = "exposed" }
exposed-json = { group = "org.jetbrains.exposed", name = "exposed-json", version.ref = "exposed" }

h2 = { group = "com.h2database", name = "h2", version.ref = "h2" }

koin-ktor = { group = "io.insert-koin", name = "koin-ktor", version.ref = "koin" }
koin-logger-slf4j = { group = "io.insert-koin", name = "koin-logger-slf4j", version.ref = "koin" }
koin-bom = { group = "io.insert-koin", name = "koin-bom", version.ref = "koin" }

postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgres" }

logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

ktor-task-scheduling-core = { group = "io.github.flaxoos", name = "ktor-server-task-scheduling-core", version.ref = "taskScheduling" }
ktor-task-scheduling-redis = { group = "io.github.flaxoos", name = "ktor-server-task-scheduling-redis", version.ref = "taskScheduling" }
ktor-task-scheduling-mongodb = { group = "io.github.flaxoos", name = "ktor-server-task-scheduling-mongodb", version.ref = "taskScheduling" }
ktor-task-scheduling-jdbc = { group = "io.github.flaxoos", name = "ktor-server-task-scheduling-jdbc", version.ref = "taskScheduling" }

kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

kotlin-test-junit = { group = "org.jetbrains.kotlin", name = "kotlin-test-junit", version.ref = "kotlin" }
jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-database-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway-postgres" }

sentry = { group = "io.sentry", name = "sentry", version.ref = "sentry" }
sentry-okhttp = { group = "io.sentry", name = "sentry-okhttp", version.ref = "sentry" }

hikaricp = { group = "com.zaxxer", name = "HikariCP", version = "5.1.0" }

logback-gelf = { group = "de.siegmar", name = "logback-gelf", version = "4.0.2" }

graphql-kotlin-ktor-server = { group = "com.expediagroup", name = "graphql-kotlin-ktor-server", version.ref = "graphql" }

[bundles]
ktor-client = [
    "ktor-client-core",
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-client-logging",
]
